#!/bin/bash
. ./.env
. ./.version

DATE=`date +%Y-%m-%d_%H-%M-%S`
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
echo ">>>>>> Package and archive all files generated by the installation  <<<<<<"
mv ./work ./${CLUSTERNAME}
mv ./.env ./${CLUSTERNAME}/.env
tar -zcf ${CLUSTERNAME}-install-${DATE}-archive.tgz ${CLUSTERNAME}
echo "
>>>
Compressed archive successfully:

The following is the information of your cluster:

Kubernetes Name:                        ${CLUSTERNAME}
Kubernetes Control Plane Endpoint:      https://${HAPROXY_IP}:6443
kubernetes Master IPs:                  ${MASTER_IPS[@]}
Kubernetes Node IPs:                    ${NODE_IPS[@]}
Kubernetes Nodepool Name:               ${NODEPOOLNAME}
Kubernetes podCIDR:                     ${KUBE_POD_CIDR}
Kubernetes serviceCIDR:                 ${KUBE_SERVICE_CIDR}
Kubernetes Network Plugin:              ${KUBE_NETWORK_PLUGIN}

Your Kubernetes master has initialized successfully!

To start using your cluster, you need to run the following as a regular user:

  mkdir -p $HOME/.kube
  sudo cp -i ${DIR}/${CLUSTERNAME}/pki/admin.conf $HOME/.kube/config
  sudo chown $(id -u):$(id -g) $HOME/.kube/config

"


